version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./config/.env
    environment:
      - MONGO_URI=mongodb://mongo_db:27017
    depends_on:
      - mongo_db
  mongo_db:
    container_name: db-container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
